package services

import (
	"errors"
	"fmt"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"
)

// ErrInvalidToken is returned when a token fails to parse, fails signature
// verification, uses an unexpected signing algorithm, or has expired.
var ErrInvalidToken = errors.New("invalid or expired token")

// TokenTTL is how long an issued token remains valid. No refresh mechanism
// exists yet, so this is a hard re-login boundary, not a renewable session.
// Exported so handlers.go can size the auth cookie's Max-Age to match.
const TokenTTL = 24 * time.Hour

// authClaims is the JWT payload: the caller's user ID and email, a random
// CSRF token, alongside the standard registered claims (expiry). Embedding
// the CSRF token as a signed claim (rather than a second cookie) is what
// lets it survive the frontend/backend living on genuinely different
// domains — see the CSRF comment on ValidateToken below.
type authClaims struct {
	UserID    string `json:"sub"`
	Email     string `json:"email"`
	CSRFToken string `json:"csrf"`
	jwt.RegisteredClaims
}

// TokenClaims is what ValidateToken returns on success: the two pieces of
// the token a caller actually needs, without exposing the JWT library's own
// claims type to every caller.
type TokenClaims struct {
	UserID    string
	CSRFToken string
}

// AuthService hashes/verifies passwords and issues/validates JWTs, holding
// the signing secret alongside its methods — matching the constructor+
// methods shape already used by Client/OpenAIClient/S3Client.
type AuthService struct {
	jwtSecret []byte
}

// NewAuthService builds an AuthService from its signing secret.
func NewAuthService(jwtSecret string) *AuthService {
	return &AuthService{jwtSecret: []byte(jwtSecret)}
}

// HashPassword returns a bcrypt hash of password, suitable for storage in
// users.password_hash.
func (s *AuthService) HashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	return string(hash), nil
}

// CheckPassword reports whether password matches hash. Callers only need a
// yes/no, so bcrypt's own error type is collapsed to a bool here.
func (s *AuthService) CheckPassword(hash, password string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}

// GenerateToken issues a signed JWT for userID/email/csrfToken, valid for
// TokenTTL. csrfToken is generated by the caller (handlers.go) so the same
// value can also be returned in the login/register JSON response body —
// the frontend needs it there, since it can never read it back out of the
// cookie (see ValidateToken).
func (s *AuthService) GenerateToken(userID, email, csrfToken string) (string, error) {
	claims := authClaims{
		UserID:    userID,
		Email:     email,
		CSRFToken: csrfToken,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(TokenTTL)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString(s.jwtSecret)
	if err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}
	return signed, nil
}

// ValidateToken parses and verifies tokenString, returning the user/CSRF
// claims it was issued with. Rejects anything not signed with HMAC (guards
// against the classic "alg: none" / algorithm-confusion JWT pitfall) as
// ErrInvalidToken, same as any other parse/signature/expiry failure.
//
// The CSRF token travels as a claim inside this signed cookie rather than a
// second, separately-readable cookie: the frontend (Vercel) and backend
// (EC2) sit on genuinely different domains in production, and a cookie is
// only ever visible to script running on the domain that set it — the
// frontend's own JS can NEVER read a cookie the backend set, no matter what
// SameSite/Secure attributes it carries. Login/register/me instead return
// this same CSRFToken value in the JSON response body (a same-origin fetch
// response, which the frontend legitimately reads), the frontend holds it
// in memory, and AuthMiddleware compares it against the X-CSRF-Token
// header. An attacker's cross-site page still can't forge that header: it
// never gets to read this response body (CORS blocks it), so it can't learn
// the value in the first place.
func (s *AuthService) ValidateToken(tokenString string) (TokenClaims, error) {
	claims := &authClaims{}
	token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (any, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, ErrInvalidToken
		}
		return s.jwtSecret, nil
	})
	if err != nil || !token.Valid {
		return TokenClaims{}, ErrInvalidToken
	}
	return TokenClaims{UserID: claims.UserID, CSRFToken: claims.CSRFToken}, nil
}
